substitutions:
  device_name: "ld2410s"
  device_name_pretty: Presence sensor
  uart_tx_pin: GPIO17
  uart_rx_pin: GPIO16

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

esphome:
  name: $device_name

logger:
  level: DEBUG
  logs:
    sensor: INFO

api:
  encryption:
    key: !secret api_password

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  ap:
    ssid: "LD2410S Fallback Hotspot"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80
  version: 3
  include_internal: true
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

external_components:
  - source: github://mobius1974/ld2410s-esphome
    components: ["ld2410s"]

uart:
  id: uart_bus
  tx_pin: ${uart_tx_pin}
  rx_pin: ${uart_rx_pin}
  baud_rate: 115200
  parity: NONE
  stop_bits: 1
  # debug:
  #  direction: BOTH
  #  dummy_receiver: false
  #  after:
  #    delimiter: "\n"
  #  sequence:
  #    - lambda: UARTDebug::log_hex(direction, bytes, ':');

ld2410s:
  uart_id: uart_bus

sensor:
  - platform: ld2410s
    target_distance:
      name: Target Distance
    calibration_progress:
      name: Calibration  progress

binary_sensor:
  - platform: ld2410s
    has_target:
      name: Presence
    has_calibration_running:
      name: Calibration running

text_sensor:
  - platform: ld2410s
    fw_version:
      name: Firmware version
    threshold_triggers:
      name: Threshold Triggers
    threshold_holds:
      name: Threshold Holds
    threshold_snrs:
      name: Threshold SNRs
    energy_values:
      name: Energy Values

number:
  - platform: ld2410s
    max_distance:
      name: Max detect distance
    min_distance:
      name: Min detect distance
    no_delay:
      name: No detect report delay
    status_reporting_frequency:
      name: Status reporting frequency
    distance_reporting_frequency:
      name: Distance reporting frequency

    threshold_trigger:
      name: Threshold Trigger
    threshold_hold:
      name: Threshold Hold
    threshold_snr:
      name: TThreshold SNR
    threshold_selected_gate:
      name: TrigThThresholdresholdger Selected Gate

button:
  - platform: ld2410s
    calibration:
      name: Start auto calibration
    factory_reset:
      name: Factory reset

select:
  - platform: ld2410s
    response_speed:
      name: Response speed

switch:
  - platform: ld2410s
    minimal_output:
      name: Minimal output
